# Use an official MySQL runtime as a parent image
FROM mysql:latest

# Set the root password and create a database
ENV MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-alcatel}
ENV MYSQL_DATABASE=${MYSQL_DATABASE:-PTT}
ENV MYSQL_USER=${MYSQL_USER:-alcatel}
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD:-alcatel}
